### PR TITLE
tbuilder: fix typos + eigen vectors computation and rotation matrices

### PR DESCRIPTION
**Pull request by sbinet**
This CL fixes a silly typo in the lab- frame rotation matrix
computation, as well as the eigen vectors computation.
This CL also fixes how the rotation matrices are defined.

Update #14.

### CODE REVIEW

**Comment by sbinet** [comment]
not sure whether this is the final say, but I do get 79 events w/o reconstruction. (compared to 100 before, and 82 w/ `sonn`)

**Comment by rmadar** [comment]
Thanks for this! I think we should still get 70 events failing the reconstructions, but it looks to me that this version seems a better starting point to find the origin of the remaining differences. So let's merge it!

**Comment by sbinet** [comment]
(I am in a meeting until ~noon, but if you can tell me which events are failing _wrt_ the C++ ones, I'll dig them up afterwards)

**Comment by rmadar** [comment]
Here are the 9 entries which are reconstructed by the C++ code but not by the go code: `0, 2, 24, 30, 44, 56, 60, 81, 85`

**Comment by sbinet** [comment]
hum... do you have the 4-vectors +miss-Et that go through `EllipseSolution::EllipseSolution(...)` for the event `0`?
using these:
```c++
                double mW= 8.037900000000000e+01;
                double mW_= 8.037900000000000e+01;
                double mt= 1.725000000000000e+02;
                double mt_= 1.725000000000000e+02;
                double mnu = 0.000000000000000e+00;
                double mnu_ = 0.000000000000000e+00;

TLorentzVector lep1(-56.843705, -49.294411, 168.804950, 184.814114);
TLorentzVector lep2(-12.150408, 51.595663, 49.461753, 72.499723);
TLorentzVector jet1(-44.565618, -50.361997, 283.036653, 290.955627);
TLorentzVector jet2(24.923737, -8.670943, 27.339602, 38.411682);

double etx= 7.855825738005946e+01;
double ety= 7.536658086618009e+01;

      EllipseSolution ellipse_sol = EllipseSolution(
                          lep1, lep2, jet1, jet2, 
                          etx, ety, mt, mt_, mW, mW_, mnu, mnu_);
                auto o = ellipse_sol.getSolution();
                printf("o: %d\n", o.size());
```

I get `o: 0`.

(not sure your test was done with smearing and with the same seed(s) for that smearing)

**Comment by sbinet** [comment]
nevermind. I do get `70` now.

**Comment by rmadar** [comment]
Amazing! What was the issue at the end (out of curiosity)? And, again, thanks!!

**Comment by sbinet** [comment]
2 silly typos. (and not sorting the eigen vectors/values as ROOT did)

**Pull request merged**
