### PR TITLE
sonn: implement a pure-Go Sonnenschein reconstruction

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
it's a first stab.

there are probably a couple of bugs still (one would need to capture the stream of random values from the C++ side and replay those on the Go side to make sure we get a bit-by-bit reproduceability)

**Comment by rmadar** [comment]
Great, this really nice!! I'll keep the two version in the same repo right now so that I can compare result (first without smearing, so no random numbers), but then yes we could defined slices/array of number to apply exactly the same smearing in both.

Would it be possible to have a new file `sonngo.go` (or whatever) so that the merge will not overwrite the current wrapper for C++ code?

**Comment by sbinet** [comment]
I am in the process of capturing the random values stream from C++ and re-using them in Go.
once that's done and validated (ie: all bugs squashed), the Go version will be completely validated against the C++ one, so the latter could go away.

probably by the end of the day.

**Comment by rmadar** [comment]
ha perfect, thanks a lot !!!

In the meanwhile I found two bugs in the C++ code (related to the method itself) so yesterday I have added few modification in `Sonnenschein.cxx` (with some cleaning also - but that's nothing), I think it's mainly:

https://github.com/rmadar/go-topquark-reco/blob/c71ec9a3069c5cbf8386527dce82f059eb4e4f13/sonn/Sonnenschein.cxx#L256-L263

and

https://github.com/rmadar/go-topquark-reco/blob/c71ec9a3069c5cbf8386527dce82f059eb4e4f13/sonn/Sonnenschein.cxx#L401

All the other modification is some printing and some convenient boolean to enable or not some features. I can take care of implementing this later on (I am planning to improve of bit the user interface for those options anyway)

**Comment by sbinet** [comment]
this version is bit-by-bit compatible w/ the one before your C++ fixes. yay!
(circling back to retro-apply your fixes, now)

**Comment by sbinet** [comment]
ok, done.

the Go and C++ version are bit-to-bit comparable (provided they get the same stream of pseudo-random numbers).
I've checked that in the `cxx-capture` branch in my fork.

I'll leave it up to you to remove the CGo code :)

**Comment by rmadar** [comment]
popopo, great, thank you very much !!

**Comment by rmadar** [comment]
I have the following error 
```
lep_v_pt.Rotate undefined (type r3.Vec has no field or method Rotate)
```
I currently have gonum `v0.8.1`. I tried to update gonum to the last commit https://github.com/gonum/gonum/commit/18580834651d292e7ef956d045f84dde7740666d#diff-b9e998b692bd644267de027a412e2cb7335a7e648f752f5995ce5ef427e6dbd2 but it doesn't work. I have something like:

```
$>go get -u -v gonum.org/v1/gonum@18580834651d292e7ef956d045f84dde7740666d
go: gonum.org/v1/gonum 18580834651d292e7ef956d045f84dde7740666d => v0.8.1-0.20201202015544-18580834651d
go: downloading gonum.org/v1/gonum v0.8.1-0.20201202015544-18580834651d
go get: inconsistent versions:
	gonum.org/v1/gonum@v0.8.1-0.20201202015544-18580834651d from gonum.org/v1/gonum@18580834651d292e7ef956d045f84dde7740666d requires gonum.org/v1/gonum@v0.8.1 (not gonum.org/v1/gonum@v0.8.1-0.20201202015544-18580834651d from gonum.org/v1/gonum@18580834651d292e7ef956d045f84dde7740666d)

```

**Comment by sbinet** [comment]
got it also...

https://github.com/gonum/gonum/issues/1523

**Comment by sbinet** [comment]
worked around w/ https://github.com/rmadar/go-topquark-reco/pull/6

**Comment by rmadar** [comment]
What is the logic behing this code?
https://github.com/rmadar/go-topquark-reco/blob/e7ec752fc690ed5d7e6cfee5c3edb2f0a0eceb5a/demo/main.go#L112-L128

Is it a relic of comparison between C++ and go, that could go away now?

**Comment by sbinet** [comment]
it was a simple way to switch between the CGo-based and pure-Go-based functions.

**Pull request merged**
