### PR TITLE
capi: first import

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by rmadar** [comment]
Thanks a lot for this! It looks simple enough to be used by an external user.

**Comment by rmadar** [comment]
I have just tried on my computer and the make file doesn't compile:
```
[rmadar@clratlport01]:capi>make
go build -v -o libcapi.so -buildmode=c-shared
capi.go:10:2: cannot find package "github.com/rmadar/go-topquark-reco/sonn" in any of:
	/usr/lib/go-1.10/src/github.com/rmadar/go-topquark-reco/sonn (from $GOROOT)
	/home/rmadar/go/src/github.com/rmadar/go-topquark-reco/sonn (from $GOPATH)
Makefile:12: recipe for target 'libcapi.so' failed
make: *** [libcapi.so] Error 1
```

Why it doesn't search the package on the web directly?

**Comment by sbinet** [comment]
could you try to first do:
```
#> cd capi
#> go install -v
#> make
```
?

**Comment by rmadar** [comment]
Thanks. I tried, but it didn't succeed (the error is the same):

```
(base) [rmadar@clratlport01]:capi>go install -v
go: downloading go-hep.org/x/hep v0.28.4-0.20201207112512-262cb50455c1
go-hep.org/x/hep/groot/rvers
go-hep.org/x/hep/groot/rcolors
go-hep.org/x/hep/groot/root
go-hep.org/x/hep/groot/rtypes
go-hep.org/x/hep/fmom
go-hep.org/x/hep/groot/rmeta
go-hep.org/x/hep/groot/internal/rcompress
go-hep.org/x/hep/rio
go-hep.org/x/hep/groot/rtree/rfunc
go-hep.org/x/hep/groot/rbytes
go-hep.org/x/hep/hbook
go-hep.org/x/hep/groot/exp/rntup
go-hep.org/x/hep/groot/rbase
go-hep.org/x/hep/groot/rphys
go-hep.org/x/hep/groot/rcont
go-hep.org/x/hep/groot/rdict
go-hep.org/x/hep/groot/rhist
go-hep.org/x/hep/hbook/rootcnv
go-hep.org/x/hep/groot/riofs
go-hep.org/x/hep/groot/rtree
go-hep.org/x/hep/groot/ztypes
go-hep.org/x/hep/groot
github.com/rmadar/go-topquark-reco/sonn
github.com/rmadar/go-topquark-reco/capi
(base) [rmadar@clratlport01]:capi>make
go build -v -o libcapi.so -buildmode=c-shared
capi.go:10:2: cannot find package "github.com/rmadar/go-topquark-reco/sonn" in any of:
	/usr/lib/go-1.10/src/github.com/rmadar/go-topquark-reco/sonn (from $GOROOT)
	/home/rmadar/go/src/github.com/rmadar/go-topquark-reco/sonn (from $GOPATH)
Makefile:12: recipe for target 'libcapi.so' failed
make: *** [libcapi.so] Error 1
```

**Comment by sbinet** [comment]
Hum...
What is the output of 'pwd'? And the output of 'go env'?

**Comment by rmadar** [comment]
### pwd
```
/home/rmadar/cernbox/goDev/go-topquark-reco/capi
```

### go env
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rmadar/.cache/go-build"
GOENV="/home/rmadar/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rmadar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/rmadar/sdk/go1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/rmadar/sdk/go1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/rmadar/cernbox/goDev/go-topquark-reco/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build433324839=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by sbinet** [comment]
could you retry after:
```
#> export GO111MODULE=on
```
(or upgrade to Go-1.15.x)

**Comment by rmadar** [comment]
`GO111MODULE=on` didn't work (same error, even after re-reunning `go install -v && make` 

I'll try to upgrade to go-1.15, but I need to check how to do it ... and: can it break some of my other package? (I first tried to just put `go 1.15` in `go.mod` but it didn't do anything so I guess it's not enough!

**Comment by sbinet** [comment]
it shouldn't impact anything (famous last words).

upgrading should be as easy as:
```
#> go get golang.org/dl/go1.15.6
#> go1.15.6 download
```

see:
- https://github.com/golang/dl
- https://godoc.org/golang.org/dl/go1.15.6

that said, let me try to replicate your issue in a docker container...

**Comment by sbinet** [comment]
and if do:
```
$> cd /home/rmadar/cernbox/goDev/go-topquark-reco
$> go get -v ./...
$> cd ./capi
$> make
```
?

**Comment by sbinet** [comment]
(my test in a fresh docker container with Go-1.14.13 installed worked)

**Comment by rmadar** [comment]
So for the record, I switched to `go1.15.6` and the following command worked
```
go build -v -x -o libcapi.so -buildmode=c-shared
```

Thanks!

**Comment by rmadar** [comment]
Actually, I think the problem is around the `make` command. I have modified the makefile to have the `-x` option and I still get the same error:
```
(base) [rmadar@clratlport01]:capi>make
go build -v -x -o libcapi.so -buildmode=c-shared
WORK=/tmp/go-build976443225
capi.go:10:2: cannot find package "github.com/rmadar/go-topquark-reco/sonn" in any of:
    /usr/lib/go-1.10/src/github.com/rmadar/go-topquark-reco/sonn (from $GOROOT)
    /home/rmadar/go/src/github.com/rmadar/go-topquark-reco/sonn (from $GOPATH)
capi.go:11:2: cannot find package "go-hep.org/x/hep/fmom" in any of:
    /usr/lib/go-1.10/src/go-hep.org/x/hep/fmom (from $GOROOT)
    /home/rmadar/go/src/go-hep.org/x/hep/fmom (from $GOPATH)
Makefile:12: recipe for target 'libcapi.so' failed
make: *** [libcapi.so] Error 1
```

while if write the same command directly in the terminal, it does work!

```
go build -v -x -o libcapi.so -buildmode=c-shared
[...]
/home/rmadar/sdk/go1.15.6/pkg/tool/linux_amd64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -installsuffix shared -buildmode=c-shared -buildid=ziVIPE0e71PyUjvfwB3k/P5NREKPstvJtyEMoe9p4/oeFYXxd0brnH2_U6sL3u/ziVIPE0e71PyUjvfwB3k -extld=gcc /home/rmadar/.cache/go-build/39/39c524cea94c6a98291be997fd99056ccc0e0e2a116bbb3826e39e2317788b0e-d
/home/rmadar/sdk/go1.15.6/pkg/tool/linux_amd64/buildid -w $WORK/b001/exe/a.out # internal
mv $WORK/b001/_cgo_install.h libcapi.h
mv $WORK/b001/exe/a.out libcapi.so
rm -r $WORK/b001/
```
And this is true without the `-x` option:
```
(base) [rmadar@clratlport01]:capi>go build -v -o libcapi.so -buildmode=c-shared
runtime/cgo
github.com/rmadar/go-topquark-reco/capi
```

So the pb is `make` since the begining, I think.

**Comment by sbinet** [comment]
btw, a priori, the resulting C shared library is a pure-C one:

```
$ ldd ./libcapi.so 
ldd: warning: you do not have execution permission for `./libcapi.so'
	linux-vdso.so.1 (0x00007ffe13fbb000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007ff60cfbd000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007ff60cdf4000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007ff60dada000)
```

so it could probably be shipped/deployed as-is.

**Comment by sbinet** [comment]
try putting the explicit path to your go1.15.6 Go binary in the make file?

as you can see from the log, it still tries to use your Go-1.10 installation.
also, perhaps add a `go env` printout just before the call to `go build` in the Makefile to see what's really going one?

**Comment by rmadar** [comment]
Yes, replace `go` by `go1.15.6` in the makefile did the trick. And before this change, I had this
```
GOROOT="/usr/lib/go-1.10"
```
while after, I got this:
```
GOROOT="/home/rmadar/sdk/go1.15.6"
```

It means that the env setup done in my `~/.basrch` are ignored when executing the makefile.

> so it could probably be shipped/deployed as-is.

This is exactly what I want. I'll try this out!

Thanks for the help (the next step will be to be able to pass all the options in the C program as well!)

**Comment by sbinet** [comment]
for the options, I'd recommend to modify `InitSonnenschein` to take all possible option values: variadic functions are tricky to interface.

_e.g.:_
```go
// capi.go

//export InitSonnenschein
func InitSonnenschein(fname *C.char, seed uint64, smearing int, nsmearing int, debug int) { ... }
```

**Comment by rmadar** [comment]
Sounds straightfoward enough to give a try! Thanks

**Pull request merged**
